### ISSUE TITLE
CSIT 142

### ISSUE THREAD

**Issue by DevaDixon** [DevaDixon/Pathway_Guide#10]
Does not appear to be reading it's prereqs properly. When the prereq is marked complete it still comes up unavailable

**Comment by thepunctuatedhorizon** [comment]
It may be because the prerequisites is not officially required. I'll have
to ponder how this can be fixed.

**Comment by thepunctuatedhorizon** [comment]
Its because the prereq is OFAD114 and OFAD114 isn't on the list as required.  And OFAD114 isn't correctly set up in the database.

**Comment by iewi** [comment]
OFAD 114 is one of the prerequisites, the other is CSIT101. You can take either of them to fulfill the prerequisite requirement, you don't have to take both.

**Comment by thepunctuatedhorizon** [comment]
```
Oh, ok.  So there is something broken in the code.  I'll try and
  find it. I won't go too indepth. 


On 7/15/2016 4:18 PM, Dorothy Carter
  wrote:


  OFAD 114 is one of the prerequisites, the other is CSIT101. You
    can take either of them to fulfill the prerequisite requirement,
    you don't have to take both.
  —
    You are receiving this because you commented.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.
```

**Comment by thepunctuatedhorizon** [comment]
I figured out why.  I didn't implement the logic for this type of class yet.  Should be easy.  I don't think I'll get it done today, though
