### ISSUE TITLE
Nursing button crash

### ISSUE THREAD

**Issue by iewi** [DevaDixon/Pathway_Guide#2]
If you're in the nursing pathway, and go to choose a new pathway, and click on the nursing button again, the app crashes.

The stack trace isn't helpful, it looks like this: [nursing_button.txt](https://github.com/DevaDixon/Pathway_Guide/files/344652/nursing_button.txt)

It's _probably_ in chooseSubPathway, but who knows?

**Comment by DevaDixon** [comment]
Issue was in chooseSubPathway. 
Decompilation artifact making an infinite loop in the onClick() method
