### ISSUE TITLE
App walkthrough (demo_info.java)

### ISSUE THREAD

**Issue by DevaDixon** [DevaDixon/Pathway_Guide#4]
While going through the walkthrough, was able to rotate screen to landscape. When screen rotated back, either the material showcase sequence or the entire activity restarted. Did not test if the other walkthrough sequences also exhibited this behavior.

**Comment by thepunctuatedhorizon** [comment]
setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
Add this to each onCreate.  ( I almost ended my sentence with ; !! hehe too much programming for me.)
