### ISSUE TITLE
Data for Double Classes Not coming out of the database

### ISSUE THREAD

**Issue by thepunctuatedhorizon** [DevaDixon/Pathway_Guide#9]
getGenEdClasses is not returning data.

**Comment by thepunctuatedhorizon** [comment]
Hehe, that's a cool feature.  Didn't know I could assign people!  I thought only Deva could do that.

**Comment by iewi** [comment]
It's less that the method isn't returning data, and more that there's no data to return.
I'm adding the gen ed courses in today.

**Comment by iewi** [comment]
Added in some gen ed courses. As a side note, you need to use getProgramElectives for PRELECT courses.
